version: '3.7'

services:
  drone-server:
    container_name: drone_server
    image: drone/drone:1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - 'DRONE_GITHUB_CLIENT_ID=${CLIENT_ID}'
      - 'DRONE_GITHUB_CLIENT_SECRET=${CLIENT_SECRET}'
      - 'DRONE_RPC_SECRET=${RPC_SECRET}'
      - 'DRONE_SERVER_HOST=${SERVER_HOST}'
      - 'DRONE_USER_CREATE=${USER_CREATE}'
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_PROTO=https
      - DRONE_TLS_AUTOCERT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
    env_file: .env

  drone-runner-docker:
    container_name: drone_agent
    image: drone/agent:1
    restart: unless-stopped
    ports:
     - 3000:3000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - 'DRONE_RPC_SECRET=${RPC_SECRET}'
     - DRONE_RPC_HOST=drone-server
     - DRONE_RUNNER_CAPACITY=4
     - DRONE_RUNNER_NAME=runner
     - DRONE_LOGS_PRETTY=true
     - DRONE_LOGS_COLOR=true
    env_file: .env
